# SkyGenCore
# grassminevn
# by Cortez Romeo

# Tăng bonus cho booster nếu người chơi có permission
pickup-permission:
   1:
      permission: 'itemgenerator.pickup.1'
      bonus: 2
      
generator:
   # check player xung quanh
   radius:
      x: 2
      y: 2
      z: 2
      
# category trong mmoitem để nhận dữ liệu
mmoitem-category: MATERIAL
      
message:
   actionbar: '&3Booster &bx%booster%'
   actionbar-1: '&eBooster &bx%booster% &e%timeformat%'
   temp-booster-actived: '&fKích hoạt thành công &dBooster tạm thời &ex%amount% &ftrong vòng %timeformat% &7&oThời gian vẫn chạy khi bạn đã thoát game'
   temp-booster-actived-add: '&fĐã cộng dồn thêm %timeformat1% &fcho &dBooster tạm thời &ex%amount% &fcủa bạn (Thời gian mới: %timeformat2%&f)'
   temp-booster-expired: '&cBooster tạm thời &ex%amount%&c của bạn đã &4&lHẾT HẠN'
   autocompressors-on: 
      - '&aBật tự chế tạo thành công &7&oXài /tuchetao một lần nữa để tắt'
      - '&aMỗi loại quặng sẽ có một quyền chế tạo riêng, có thể tìm thấy và trao đổi các quyền đó ở &e/warp trade'
      - '&aThời gian tự chế tạo của bạn là: &e%time% giây&a. Mua &e/rank&a sẽ cung cấp thời gian tự chế tạo nhanh hơn'
   autocompressors-off: '&cTắt tự chế tạo thành công &7&oXài /tuchetao một lần nữa để bật'
   blockName:
      DIRT: '&6Khối Đất'
      AMETHYST_SHARD: '&dMảnh Thạch Anh Tím'
      PURPLE_DYE: '&dBột Nhuộm Tím'
      STONE: '&7Khối Đá'
      WARPED_BUTTON: '&3Nút Kì Dị'
      PUMPKIN_SEEDS: '&fHạt Bí Ngô'
      SAND: '&eKhối Cát'
      REDSTONE: '&cĐá Đỏ'
      PINK_DYE: '&dBột Nhuộm Hồng'
      NETHERITE_INGOT: '&7Phôi Netherit'
      IRON_INGOT: '&fPhôi Sắt'
      GRASS: '&aCỏ'
      GOLD_INGOT: '&ePhôi Vàng'
      ACACIA_BUTTON: '&6Nút Gỗ Xiêm Gai'
      DIAMOND: '&bKim Cương'
      COPPER_INGOT: '&6Phôi Đồng'
      NETHER_WART: '&cBướu Nether'
      COAL: '&8Than'
      STONE_BUTTON: '&7Nút Đá'
      RED_DYE: '&cBột Nhuộm Đỏ'
      COCOA_BEANS: '&6Hạt Ca Cao'
      MELON_SEEDS: '&6Hạt Dưa Hấu'
      ORANGE_DYE: '&6Bột Nhuộm Cam'
      BONE: '&fXương'
      GOLD_NUGGET: '&eHạt Vàng'
      AMETHYST_CLUSTER: '&dCụm Thạch Anh Tím'
      # có thể thêm display name cho mmoitem
      RARE_DIAMOND: "&bRare Diamond"
      MAGIC_ESSENCE: "&5Magic Essence"
   genlist:
       - '&e[1] &6Dirt'
       - '&e[2] &7Stone'
       - '&e[3] &fIron'

# Phần thời gian hiển thị      
time-format:
   wwddhhmmss: '&a%w% &ftuần &a%d% &fngày &a%h% &fgiờ &a%m% &fphút &a%s% &fgiây' 
   ddhhmmss: '&a%d% &fngày &a%h% &fgiờ &a%m% &fphút &a%s% &fgiây' 
   ddhhmmss: '&a%d% &fngày &a%h% &fgiờ &a%m% &fphút &a%s% &fgiây'   
   hhmmss: '&a%h% &fgiờ &a%m% &fphút &a%s% &fgiây'
   mmss: '&a%m% &fphút &a%s% &fgiây'
   ss: '&a%s% &fgiây'
   
# Tự chế tạo
auto-compressors: 
   compressors:
      tuchetao1:
         permission: 'skygen.compressors.dirt' 
         item-required:
            MATERIAL_BEDROCK: 64
         new-item: DIRT2