name: SkyGenCore
main: grassminevn.skygencore.Main
author: Cortez_Romeo
version: ${project.version}
api-version: 1.14
load: POSTWORLD
depend:
   - PlaceholderAPI
softdepend:
   - MMOItems   
commands:
   skygencore:
      aliases:
         - core
   kichhoatbooster:
      aliases:
         - khb
   genlist:
   autocompressors:
      aliases:
      - tuchetao
      - autocraft
      - autotrade
      - autoc
      - autochetao   